repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: workflow-dev
        name: development workflow automation
        description: Run cargo make workflow-dev
        entry: cargo make
        language: system
        args: ["--makefile", "workflow-dev.toml", "workflow-dev"]
        types: [rust]
